version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    target-branch: "master"
    open-pull-requests-limit: 5
    assignees:
      - "bendrucker"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"